### ISSUE TITLE
LC API Bugged

### ISSUE THREAD

**Issue by Ashcalon** [u-2018/LC-API#46]
https://github.com/u-2018/LC-API/assets/136176846/d0f0fc21-ce71-4a5b-b30e-9b8e37d42ae6

There seems to be a bug in the LC API causing dummies to appear, preventing me from interacting.

The version I have currently used is as follows:
- Bepinex 5.4.2100
- LC API 3.1.0.

I installed this mod by manual installation

**Comment by gage64** [comment]
this bug also happened to me just once. but in my case, it didn't allow me to move at all and had to remake a lobby to fix it

**Comment by ghost** [comment]
I've been experiencing the exact same issue, it also does not let me join any lobby and when i host "Player #"'s show up.
No idea what could be causing it, been a big pain in my bottom.

**Comment by catgocri** [comment]
also have this error

**Comment by Kaspian24** [comment]
Same issue, I also cannot move or open menu. I installed it manually. It works fine for a friend of mine who installed it via Thunderstore Mod Manager.

**Comment by catgocri** [comment]
it seems to only occur when using a manual installation of mods, as when I tried launching through thunderstore the error disappeared.

**Comment by Kaspian24** [comment]
Using r2modman everything works fine too.

**Comment by steven4547466** [comment]
The bundles folder should be in the 2018-LC_API folder, like this:
![4ubwo2_17954 1](https://github.com/u-2018/LC-API/assets/23726534/d43a58af-1ab2-4a6c-93ef-b8e7aa36c6cb)

The Bundles folder in the BepinEx folder is legacy and not used. If you're wondering why the zip puts Bundles right in the plugins folder, it's because that's how thunderstore wants it and when installing with a mod manager, it will automatically put anything in the plugins folder into a folder called `AUTHOR-PLUGIN`

If this doesn't fix your issue, reopen.
