### ISSUE TITLE
Bundle API is preventing other mods from loading their bundles.

### ISSUE THREAD

**Issue by EvaisaDev** [u-2018/LC-API#7]
Your new bundle system is preventing other mods which DO NOT use your API from loading asset bundles manually.
Because your mod is just loading bundles from every mod folder and unity can only load an asset bundle once.
So when a mod loaded after your API tries to load a bundle manually it is unable to do so.

Please just remove the bundle API in all honesty, it is solving a non existent problem, loading an asset bundle is literally 1 line of code without any API.

Either that or make it not load a bundle without consent.

**Comment by legoandmars** [comment]
#9 should fix this temporarily without any major code changes

**Comment by legoandmars** [comment]
If the main goal of this is keeping legacy bundle support, ideally in the end either:
- Every mod using the legacy API should just update
- Legacy API support exists, but only for an extremely strict subset of legacy mods, such as only loading a bundle if they have a specific filename from a dictionary. EG: "LC_Construct.bundle" or whatever would be loaded because it's explicitly been used in an older mod, but "RandomBundle.bundle" wouldn't because it's new
